apiVersion: v1
kind: Pod
metadata:
  name: ellipses-app
  labels:
    app: myapp
spec:
  containers:
  - name: ellipses-app
    image: 127.0.0.1:5000/ellipses
    resources: {}
    ports:
      - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - port: 5002
  type: NodePort

